---

- name: reload apache2
  service:
    name: apache2
    state: reloaded
    enabled: yes
  become: yes

- name: restart mariadb
  service:
    name: mariadb
    state: restarted
    enabled: yes
  become: yes
